version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - mock-server
    networks:
      - app-network

  mock-server:
    build:
      context: .
      dockerfile: Dockerfile.mock
    environment:
      - NODE_ENV=production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 