FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .


HEALTHCHECK --interval=30s --timeout=3s \
  CMD wget --quiet --tries=1 --spider http://localhost:3000/api/show_profile_me || exit 1

EXPOSE 3000

CMD ["npm", "start"] 